import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getSession } from "@/app/config/auth"
import { Toaster } from 'sonner'
// import { SocketProvider } from '@/app/contexts/SocketContext';

import SessionProvider from '@/app/config/SessionProvider'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession()
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider session={session}>
         {/* <SocketProvider> */}
          <Toaster />
          {children}
        {/* </SocketProvider> */}
       </SessionProvider>
       {/* <script src="https://cdn.jsdelivr.net/pnpm/@digitalpersona/fingerprint@1.0.0/dist/fingerprint.sdk.min.js"></script> */}
      </body>
    </html>
  );
}
